apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-server
  labels:
    {{- include "petclinic.labels" (dict "Release" .Release "Chart" .Chart "component" "admin-server") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.adminServer.port }}
      targetPort: {{ .Values.adminServer.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "petclinic.selectorLabels" (dict "Release" .Release "component" "admin-server") | nindent 4 }}
