apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: tungnc2012/spring-petclinic-config-server:1.0.0
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "128m"
            memory: "256Mi"
          requests:
            cpu: "128m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10 