services:
  # Application services - Start after observability stack
  config-server:
    image: tungnc2012/spring-petclinic-config-server:1.0.0
    container_name: config-server
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
     - 8888:8888
    networks:
      - petclinic-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  discovery-server:
    image: tungnc2012/spring-petclinic-discovery-server:1.0.0
    container_name: discovery-server
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
     - 8761:8761
    networks:
      - petclinic-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  customers-service:
    image: tungnc2012/spring-petclinic-customers-service:1.0.0
    container_name: customers-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_started
    ports:
    - 8082:8082
    networks:
      - petclinic-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp

  visits-service:
    image: tungnc2012/spring-petclinic-visits-service:1.0.0
    container_name: visits-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_started
    ports:
     - 8084:8084
    networks:
      - petclinic-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp

  vets-service:
    image: tungnc2012/spring-petclinic-vets-service:1.0.0
    container_name: vets-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_started
    ports:
     - 8083:8083
    networks:
      - petclinic-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp

  # genai-service:
  #   image: tungnc2012/spring-petclinic-genai-service:1.0.0
  #   container_name: genai-service
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
  #     - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #   depends_on:
  #     config-server:
  #       condition: service_started
  #     discovery-server:
  #       condition: service_started
  #   ports:
  #    - 8085:8085
  #   networks:
  #     - petclinic-network
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: tungnc2012/spring-petclinic-api-gateway:1.0.0
    container_name: api-gateway
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_started
    ports:
     - 8081:8081
    networks:
      - petclinic-network

  admin-server:
    image: tungnc2012/spring-petclinic-admin-server:1.0.0
    container_name: admin-server
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_started
    ports:
     - 9099:9099
    networks:
      - petclinic-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  petclinic-network:
    name: obser-stack-docker_petclinic-network
    external: true