spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production

otel:
  instrumentation:
    micrometer:
      enabled: true
    service:
      name: vets-service
    exporter:
      otlp:
        endpoint: http://otel-collector:4318
        logging:
          enabled: true
        metrics:
          enabled: true
        traces:
          enabled: true
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
