{{- if or .Values.genaiService.openaiApiKey .Values.genaiService.azureOpenaiKey .Values.genaiService.azureOpenaiEndpoint }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-genai-secret
  labels:
    {{- include "petclinic.labels" (dict "Release" .Release "Chart" .Chart "component" "genai-service") | nindent 4 }}
type: Opaque
data:
  {{- if .Values.genaiService.openaiApiKey }}
  openai-api-key: {{ .Values.genaiService.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.genaiService.azureOpenaiKey }}
  azure-openai-key: {{ .Values.genaiService.azureOpenaiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.genaiService.azureOpenaiEndpoint }}
  azure-openai-endpoint: {{ .Values.genaiService.azureOpenaiEndpoint | b64enc | quote }}
  {{- end }}
{{- end }}
