apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-genai-service
  labels:
    {{- include "petclinic.labels" (dict "Release" .Release "Chart" .Chart "component" "genai-service") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.genaiService.port }}
      targetPort: {{ .Values.genaiService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "petclinic.selectorLabels" (dict "Release" .Release "component" "genai-service") | nindent 4 }}
