# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: genai-service
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: genai-service
#   template:
#     metadata:
#       labels:
#         app: genai-service
#     spec:
#       containers:
#       - name: genai-service
#         image: tungnc2012/spring-petclinic-genai-service:1.0.0
#         ports:
#         - containerPort: 8085
#         resources:
#           limits:
#             cpu: "128m"
#             memory: "256Mi"
#           requests:
#             cpu: "128m"
#             memory: "256Mi"
#         env:
#         - name: OPENAI_API_KEY
#           value: "<your-openai-api-key>"
#         - name: AZURE_OPENAI_KEY
#           value: "<your-azure-openai-key>"
#         - name: AZURE_OPENAI_ENDPOINT
#           value: "<your-azure-openai-endpoint>"
#         readinessProbe:
#           httpGet:
#             path: /actuator/health
#             port: 8085
#           initialDelaySeconds: 10
#           periodSeconds: 5
#         livenessProbe:
#           httpGet:
#             path: /actuator/health
#             port: 8085
#           initialDelaySeconds: 30
#           periodSeconds: 10 