spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

otel:
  instrumentation:
    micrometer:
      enabled: true
    service:
      name: customers-service
    exporter:
      otlp:
        endpoint: http://otel-collector:4318
        logging:
          enabled: true
        metrics:
          enabled: true
        traces:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "metrics"

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
